### ISSUE TITLE
SFTP uploading taking lot of time

### ISSUE THREAD

**Issue by DorvakOff** [wangyucode/sftp-upload-action#11]
Hello, the uploading of files is taking too much time (4min39s) for only 45mb

``` 
  deploy:
    name: Deploying to the server
    runs-on: ubuntu-latest
    needs: [ compile-jar, update-version ]
    steps:
      - name: Restore the stored App from artifacts
        uses: actions/download-artifact@v2
        with:
          path: build
      - name: Moving files to root
        run: mv build/App/* ./
      - name: Clearing extras
        run: rm -r build
      - name: Listing files
        run: tree
      - name: SFTP Deploy
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: ${{ secrets.SFTP_ADDRESS }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PWD }}
          port: 2022
          localDir: './'
          remoteDir: './'
          dryRun: false
```

![image](https://user-images.githubusercontent.com/50071842/194779712-38a4ba24-9f9d-4905-8648-48fc3e1df128.png)
