### ISSUE TITLE
Files are not uploading

### ISSUE THREAD

**Issue by mgbell** [wangyucode/sftp-upload-action#6]
Thanks for this action.  I'm not getting any errors when my workflow runs but it doesn't seem to be uploading the files.

My workflow file is as follows:

``` 
name: Staging Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    
    - name: SFTP Upload to Cloudways
      uses: wangyucode/sftp-upload-action@v1.3.3
      with:
        host: ${{ secrets.STAGING_FTP_HOST }}
        username: ${{ secrets.STAGING_FTP_USER }}
        password: ${{ secrets.STAGING_FTP_PASSWORD }}
        localDir: '././'
        remoteDir: '/public_html/'

```

I think it may be an issue with my localdir directive, but I have tried leaving it blank, and using ``` / ``` , ``` ./ ```, and simply ``` . ``` without any luck.

Am I being very dense?

Thanks in advance.
